export const profile = {
  data: {
    education: [
      [
        {
          id: 7789,
          uuid: "b496c38e-517a-4482-adb2-1c6ac29603ef",
          location: "Kolkata",
          end_date: "2020",
          start_date: "2020",
          course: "Bachelor of Engineering",
          department: "Fine Arts",
          institution_id: 6598,
          institution_name: "University of Calcutta",
          institution_logo_url: null,
          score: null,
          score_metric_value: "4",
          score_metric: "Division",
          duration: "1 year",
        },
      ],
      1,
    ],
    projects: [],
    certifications: [],
    workex: [
      [
        {
          uuid: "945a6a8a-3011-40ac-88da-915a6f94bd90",
          id: 29994,
          location: "Bangalore, Karnataka, India",
          location_name: "Bangalore",
          status: 0,
          designation: "Sr. Frontend Lead",
          end_date: "Present",
          start_date: "Jul 2021",
          claimed_by: "user",
          skills_data: [
            {
              id: 39000,
              skill_id: 27356,
              skill_name: "react.js",
            },
            {
              id: 39001,
              skill_id: 19,
              skill_name: "javascript",
            },
            {
              id: 39002,
              skill_id: 34053,
              skill_name: "typescript",
            },
          ],
          level: null,
          description: null,
          role: "team",
          l1_completed: false,
          l3_completed: false,
          l1_completed_at: null,
          l3_completed_at: null,
          duration: "3 years, 2 months",
          company: {
            id: 19814,
            uuid: "fba4bea9-7ecb-4321-b9b9-47952a7798f7",
            status: 0,
            type: "company",
            entity_id: "Cfba4bea9-7ecb-4321-b9b9-47952a7798f7",
            name: "Mindtree",
            logo_url: "https://logo.clearbit.com/mindtree.com",
            avatar_url: "https://logo.clearbit.com/mindtree.com",
            bio: null,
            vanity_name: null,
            domain: null,
            tld: null,
            serialized: true,
          },
        },
        {
          uuid: "8a7b8175-e102-4ea2-833e-dc8b617fdd97",
          id: 29993,
          location: "Bangalore, Karnataka, India",
          location_name: "Bangalore",
          status: 0,
          designation: "Sr. Software Engineer",
          end_date: "Jul 2021",
          start_date: "Oct 2020",
          claimed_by: "user",
          skills_data: [
            {
              id: 38991,
              skill_id: 27356,
              skill_name: "react.js",
            },
            {
              id: 38992,
              skill_id: 242,
              skill_name: "node.js",
            },
            {
              id: 38993,
              skill_id: 1,
              skill_name: "Python",
            },
          ],
          level: null,
          description: null,
          role: "pastemployee",
          l1_completed: false,
          l3_completed: false,
          l1_completed_at: null,
          l3_completed_at: null,
          duration: "10 months",
          company: {
            id: 19813,
            uuid: "f31470c6-540b-4b62-a95b-2396605255b1",
            status: 0,
            type: "company",
            entity_id: "Cf31470c6-540b-4b62-a95b-2396605255b1",
            name: "BORN Group",
            logo_url: "https://logo.clearbit.com/borngroup.com",
            avatar_url: "https://logo.clearbit.com/borngroup.com",
            bio: null,
            vanity_name: null,
            domain: null,
            tld: null,
            serialized: true,
          },
        },
        {
          uuid: "af9e8048-d402-4fb5-b71d-c1f4b3220454",
          id: 26998,
          location: "Karnataka, India",
          location_name: "Karnataka",
          status: 0,
          designation: "Software Engineer",
          end_date: "Sep 2020",
          start_date: "Feb 2020",
          claimed_by: "user",
          skills_data: [
            {
              id: 38985,
              skill_id: 34053,
              skill_name: "typescript",
            },
            {
              id: 38986,
              skill_id: 19,
              skill_name: "javascript",
            },
            {
              id: 38987,
              skill_id: 27356,
              skill_name: "react.js",
            },
            {
              id: 38994,
              skill_id: 34053,
              skill_name: "typescript",
            },
            {
              id: 38995,
              skill_id: 19,
              skill_name: "javascript",
            },
            {
              id: 38996,
              skill_id: 27356,
              skill_name: "react.js",
            },
            {
              id: 38997,
              skill_id: 34053,
              skill_name: "typescript",
            },
            {
              id: 38998,
              skill_id: 19,
              skill_name: "javascript",
            },
            {
              id: 38999,
              skill_id: 27356,
              skill_name: "react.js",
            },
          ],
          level: null,
          description: null,
          role: "team",
          l1_completed: false,
          l3_completed: false,
          l1_completed_at: null,
          l3_completed_at: null,
          duration: "8 months",
          company: {
            id: 1,
            uuid: "54794860-465e-4ec3-94ef-8a256523b0f4",
            status: 4,
            type: "company",
            entity_id: "C54794860-465e-4ec3-94ef-8a256523b0f4",
            name: "SpringRole",
            logo_url:
              "https://springrole-assets.imgix.net/company/54794860-465e-4ec3-94ef-8a256523b0f4/2dfc7cf1-2bce-4c90-9ef9-2a4886786c1e.png?h=1024&w=1024",
            url: "https://www.springrole.com/company/springrole",
            avatar_url:
              "https://springrole-assets.imgix.net/company/54794860-465e-4ec3-94ef-8a256523b0f4/2dfc7cf1-2bce-4c90-9ef9-2a4886786c1e.png?h=1024&w=1024",
            bio: "Blockchain powered attestation protocol for verifying professional profiles. Create your profile now on our live beta and join us in building a trusted network.",
            vanity_name: "springrole",
            domain: [
              {
                link: "https://springrole.com",
                domain: "springrole.com",
                tld: "springrole.com",
              },
            ],
            tld: ["springrole.com"],
            vanity_entity_id: "fe019b25-e8c7-11e8-910e-0a4565e90bd0",
            serialized: true,
          },
        },
      ],
      3,
    ],
    messagePrice: 0,
    ethAddress: ["0x489Db2Bfe2083B8Dc4a262A797417Dd3d048239c"],
    writtenToBlockchain: false,
    usersPreferences: [
      {
        id: 190787,
        user_id: 57274,
        preference_key: "seenIntroFreelance",
        preference_value: "true",
        created_at: "2020-04-08T06:23:11.000Z",
        updated_at: "2020-04-08T06:23:11.000Z",
      },
    ],
    pendingRequests: {
      skillEndorsementCount: 0,
      pendingWorkExCount: 0,
      pendingWorkExTxCount: 0,
    },
    skills: [
      {
        id: 50565,
        skill_id: 19,
        skill_name: "Javascript",
        score: 0,
        source: "Direct",
        percentile_group: 1,
        endorsed_by: {
          total_count: 0,
          users: [],
        },
        user_has_endorsed: {
          has_endorsed: false,
        },
      },
      {
        id: 54025,
        skill_id: 242,
        skill_name: "Node.js",
        score: 0,
        source: "Direct",
        percentile_group: 1,
        endorsed_by: {
          total_count: 0,
          users: [],
        },
        user_has_endorsed: {
          has_endorsed: false,
        },
      },
      {
        id: 50563,
        skill_id: 27356,
        skill_name: "React.js",
        score: 0,
        source: "Direct",
        percentile_group: 1,
        endorsed_by: {
          total_count: 0,
          users: [],
        },
        user_has_endorsed: {
          has_endorsed: false,
        },
      },
    ],
    freelance: {
      seenGetStarted: true,
      data: [],
    },
    verificationPercentage: 20,
    user_details: {
      name: "Dipankar Halder",
      avatar_url: "https://ui-avatars.com/api/?size=300&name=Dipankar+Halder",
      url: "https://www.springrole.com/dipankar",
      bio: "Software Engineer 6+ years of experience in Web application development. I also worked in ChatBots and BlockChain.",
      current_job_designation: null,
      current_location: "Bangalore, Karnataka, India",
      current_company: null,
      displayName: "Dipankar",
      entity_id: 70415,
      user_id: 57274,
      user_uuid: "a2955ddf-7600-4446-9128-3f58ac957d24",
      headline: {
        profile_headline_id: 29994,
        profile_headline_type: "WORKEXPERIENCE",
      },
      email: "webmail.dip@gmail.com",
      vanity_name: "dipankar",
    },
  },
};
